apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: app-space
type: Opaque
stringData:
  DATA_SOURCE_NAME: "{{ .Values.mysql.user }}:{{ .Values.mysql.password }}@({{ .Values.mysql.host }}:{{ .Values.mysql.port }})/"
