{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter-servicemonitor
  namespace: {{ .Values.serviceMonitor.namespace }}
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  namespaceSelector:
    matchNames:
      - app-space
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
