provider: aws
aws:
  region: eu-west-2

policy: sync

registry: txt

txtOwnerId: mubashir-cluster

sources:
  - service
  - istio-gateway

domainFilters:
  - mubashir.site


serviceAccount:
  create: false
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: "${role_arn}"