clusterName: "eks-cluster"
clusterEndpoint: "https://D140E5E7B502874375D0422E806CA076.yl4.eu-west-2.eks.amazonaws.com"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::038774803581:role/karpenter-controller-role"

settings:
  aws:
    interruptionQueueName: "karpenter-spot-events"

aws:
  defaultInstanceProfile: "eks-node-group-profile"