alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: "email-alert"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - match:
            severity: critical
          receiver: "email-alert"

    receivers:
      - name: "email-alert"
        email_configs:
          - to: "stokemubashir@gmail.com"
            from: "alerts@example.com"
            smarthost: "smtp.gmail.com:587"
            auth_username: "stokemubashir@gmail.com"
            auth_password: "xiwkoekzbcbxqwtn"
            require_tls: true
            
##Scraped Istiod stats- scraping the http-monitoring port:
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'istiod'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - istio-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: istiod;http-monitoring

      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus    
        kubernetes_sd_configs:
          - role: pod                     
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]  
            action: keep
            regex: '.*-envoy-prom'        
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:15090
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
