apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: app-space
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: quay.io/prometheus/mysqld-exporter:latest
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: DATA_SOURCE_NAME
