redisAddress: "redis://redis.database-monitoring.svc.cluster.local:6379"

existingSecret: redis-secret
existingSecretPasswordKey: REDIS_PASSWORD

serviceAccount:
  create: true
  automountServiceAccountToken: false

serviceMonitor:
  enabled: true
  namespace: database-monitoring
  interval: 15s
  labels:
    release: prometheus