name: Destroy Infrastructure

on:
  push:
    branches: [master]

env:
  AWS_REGION: eu-west-2
  EKS_CLUSTER_NAME: eks-cluster
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }} 

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

  
    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

   
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

  
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Configure kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name eks-cluster

  
    - name: Terraform Destroy
      working-directory: ./terraform
      run: terraform destroy --auto-approve