#app-space = Used for application workloads such as cart,catalogue,dispatch
#data-space = databases
#monitoring = Prometheus, grafana and exporters
#argocd = Gitops

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam:038774803581:user/terraform-test
      username: admin
      groups:
        -system:
---
##MySql Service Account

apiVersion: v1
kind: ServiceAccount
metadata:
    name: mysql-sa
    namespace: app-space


###RBAC Role so only the Mysql stateful set can read secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-secret-reader
  namespace: app-space
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["mysql-secret"]
  verbs: ["get", "watch", "list"]
---

###RBAC RoleBinding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-read-secrets
  namespace: app-space
subjects:
- kind: ServiceAccount
  name: mysql-sa
roleRef:
  kind: Role
  name: mysql-secret-reader
  apiGroup: rbac.authorization.k8s.io


