############################################
# DATA-SPACE SERVICES (separate)
############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.mongoappName }}
  namespace: {{ .Values.databaseNamespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ Values.mongoappName }}
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.mysqlappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.mysqlappName }}
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.redisappName }}
  namespace: {{ .Values.databaseNamespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ Values.redisappName }}
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.rabbitmqappName }}
  namespace: {{ .Values.databaseNamespace }}
spec:
  selector:
    app: {{ Values.rabbitmqappName }}
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

---

############################################
# APP-SPACE SERVICES (separate)
############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.cartappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.cartappName }}
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: {{ Values.catalogueappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.catalogueappName }}
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.dispatchappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.dispatchappName }}
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.paymentsvcname }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: robotshop-payment 
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: {{ Values.ratingssvcname }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: robotshop-ratings
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.shippingappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.shippingappName }}
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ Values.userappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.userappName }}
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: {{ Values.webappName }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.webappName }}
    version: v1
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: {{ Values.canarywebname }}
  namespace: {{ .Values.appNamespace }}
spec:
  selector:
    app: {{ Values.webappName }}
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: load-gen
  namespace: app-space
spec:
  selector:
    app: load-gen
    version: v1
  ports:
  - port: 8080
    targetPort: 8080