FROM node:25-alpine3.22 AS builder

WORKDIR /opt/server

# Copy only package files first (better cache)
COPY package.json ./

# Install production deps only
RUN npm install --omit=dev

# Copy app source
COPY server.js ./

FROM node:25-alpine3.22 AS runtime

ENV INSTANA_AUTO_PROFILE=true
ENV NODE_ENV=production

WORKDIR /opt/server

# Copy node_modules + app from builder
COPY --from=builder /opt/server /opt/server

EXPOSE 8080

CMD ["node", "server.js"]
