FROM node:25-alpine3.22 AS builder

WORKDIR /opt/server

COPY package.json ./


RUN npm install --omit=dev

COPY server.js ./

FROM node:25-alpine3.22 AS runtime

ENV INSTANA_AUTO_PROFILE=true
ENV NODE_ENV=production

WORKDIR /opt/server


COPY --from=builder /opt/server /opt/server

EXPOSE 8080

CMD ["node", "server.js"]
