replicaCount: 1

mysql:
  host: mysql
  port: 3306
  user: metrics_user
  password: metrics_password

service:
  name: mysql-exporter
  port: 9104

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 30s
