name: Intialise Terraform Code and Apply

#Workflow Triggers
on:
  push:
    branches:
      - master
      
##Environment Variables
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_CREDENTIALS: ${{ secrets.AWS_ROLE_ARN }}
  
#Define Jobs
jobs:
  terraform:
    name: "Deploy Infrastructure to Cloud"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      security-events: write

    steps:

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         aws-region: ${{ vars.AWS_REGION }}


    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    
    - name: Terraform init
      working-directory: ./terraform
      run: terraform init 

    

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

  
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply --auto-approve

    - name: Wait for EKS cluster
      run: |
        echo "Waiting 60 seconds for EKS cluster to become ready..."
        sleep 60

    - name: Update kubeconfig after apply 
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name eks-cluster





    

    

    