name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        type: choice
        options: [plan, apply, destroy]
        default: plan


env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.13.3
  TF_STATE_KEY: envs/dev/eks/terraform.tfstate


concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    name: "Terraform Infrastructure"
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./terraform
    permissions:
      id-token: write
      contents: read
      security-events: write

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

     
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.S3_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true"
     
      
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate 

        
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0
          cache: true

      - name: Terraform Lint
        run: |
          tflint --init
          tflint
  
      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check -recursive
      
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@v12
        with:
         output_format: cli,sarif
         output_file_path: console,results.sarif
         soft_fail: true
         check: HIGH,CRITICAL
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        
        if: success() || failure()
        with:
          sarif_file: results.sarif

      
      - name: Terraform Plan
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        run: terraform plan -out=tfplan

      
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

     
      - name: Install kubectl
        if: github.event.inputs.action == 'apply'
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      - name: Update kubeconfig
        if: github.event.inputs.action == 'apply'
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name eks-cluster